enabled: true
additional_trustees:
  - ericharper
  - ko3n1g
  - chtruong814
  - thomasdhc
  - pablo-garay
  - oyilmaz-nvidia
  - pthombre
  - athitten
  - janekl
additional_vetters:
  - ericharper
  - ko3n1g
  - chtruong814
  - thomasdhc
  - pablo-garay
  - oyilmaz-nvidia
  - pthombre
  - athitten
  - janekl
auto_sync_draft: false
auto_sync_ready: true
