# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM nvcr.io/nvidia/pytorch:25.05-py3
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    git \
    curl \
    libopenmpi-dev \
    vim && \
    rm -rf /var/lib/apt/lists/*

# Install uv and python
ARG UV_VERSION=0.7.2
ENV PATH="/root/.local/bin:$PATH"
RUN curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | sh
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"
ENV UV_LINK_MODE=copy

# Install all
WORKDIR /workspace
ARG INFERENCE_FRAMEWORK
RUN --mount=type=bind,source=pyproject.toml,target=/workspace/pyproject.toml \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=nemo_export/__init__.py,target=/workspace/nemo_export/__init__.py \
    --mount=type=bind,source=nemo_deploy/__init__.py,target=/workspace/nemo_deploy/__init__.py \
    --mount=type=bind,source=nemo_export_deploy_common/package_info.py,target=/workspace/nemo_export_deploy_common/package_info.py bash -exu <<"EOF"
    uv venv ${UV_PROJECT_ENVIRONMENT} --system-site-packages
    uv sync --link-mode symlink --locked 
    if [ -n "$INFERENCE_FRAMEWORK" ]; then
        uv sync --link-mode copy --locked --extra te --no-install-package torch --no-install-package torchvision --extra $INFERENCE_FRAMEWORK
    else
        uv sync --link-mode copy --locked --extra te
    fi
    # Install nemo-run separately since it conflicts with nvidia-pytriton
    uv pip install nemo-run
EOF

# Install development versions
ARG NEMO_REF
ARG MCORE_REF
RUN bash -exu <<"EOF"
    if [ -n "$NEMO_REF" ]; then
        uv pip install --no-cache-dir --upgrade --force-reinstall --no-deps \
            nemo_toolkit[automodel,common-only,nlp-only,eval,multimodal-only]@git+https://github.com/NVIDIA/NeMo.git@${NEMO_REF}
    fi
    
    if [ -n "$MCORE_REF" ]; then
        uv pip install --no-cache-dir --upgrade --force-reinstall --no-deps \
            megatron-core@git+https://github.com/NVIDIA/Megatron-LM.git@${MCORE_REF}
    fi
EOF

# For trt-llm
ENV LD_LIBRARY_PATH=/opt/hpcx/ucx/lib:$LD_LIBRARY_PATH
