# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    git \
    curl \
    libopenmpi-dev \
    vim &&
    rm -rf /var/lib/apt/lists/*

# Install uv and python
ARG UV_VERSION=0.7.2
ENV PATH="/root/.local/bin:$PATH"
RUN curl -LsSf https://astral.sh/uv/${UV_VERSION}/install.sh | sh

# Align C++ ABI for PyTorch and trt-llm
ENV CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="$UV_PROJECT_ENVIRONMENT/bin:$PATH"
ENV UV_LINK_MODE=copy

# Install all
WORKDIR /workspace
ARG INFERENCE_FRAMEWORK
RUN --mount=type=bind,source=pyproject.toml,target=/workspace/pyproject.toml \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=nemo_export/__init__.py,target=/workspace/nemo_export/__init__.py \
    --mount=type=bind,source=nemo_deploy/__init__.py,target=/workspace/nemo_deploy/__init__.py \
    --mount=type=bind,source=nemo_export_deploy_common/package_info.py,target=/workspace/nemo_export_deploy_common/package_info.py bash -exu <<"EOF"
    uv venv ${UV_PROJECT_ENVIRONMENT}
    uv sync --link-mode symlink --locked 
    if [ -n "$INFERENCE_FRAMEWORK" ]; then
        uv sync --link-mode symlink --locked --extra te --extra $INFERENCE_FRAMEWORK
    else
        uv sync --link-mode symlink --locked
    fi
    # Install nemo-run separately since it conflicts with nvidia-pytriton
    uv pip install nemo-run
EOF

# Install development versions
ARG NEMO_REF=259d684e73c45091f0b6144342133e6ceb7e824c
ARG MCORE_REF=54afff44f29e1117b2057ced6fa5be583e35cb7b
RUN uv pip install --no-cache-dir --upgrade --force-reinstall --no-deps \
    megatron-core@git+https://github.com/NVIDIA/Megatron-LM.git@${MCORE_REF} \
    nemo_toolkit[automodel,common-only,nlp-only,eval,multimodal-only]@git+https://github.com/NVIDIA/NeMo.git@${NEMO_REF}
