# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    git \
    libopenmpi-dev \
    vim \
    && rm -rf /var/lib/apt/lists/* && \
    python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir -U pip setuptools

# Set venv as default
ENV PATH="/opt/venv/bin:$PATH"

# Align C++ ABI for PyTorch and trt-llm
ENV CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"

# Install build deps: Mostly required since TransformerEngine needs `--no-build-isolation` 
# and therefore these deps need to be installed in the global scope.
RUN pip install --no-cache-dir -U \
    setuptools>=45 \
    wheel \
    torch==2.6.0 \
    wheel_stub \
    pybind11 \
    Cython>=3.0.0

# Install all
WORKDIR /workspace
RUN --mount=type=bind,source=setup.py,target=/workspace/setup.py \
    --mount=type=bind,source=nemo_export/__init__.py,target=/workspace/nemo_export/__init__.py \
    --mount=type=bind,source=nemo_deploy/__init__.py,target=/workspace/nemo_deploy/__init__.py \
    --mount=type=bind,source=package_info.py,target=/workspace/package_info.py \
    --mount=type=bind,source=README.md,target=/workspace/README.md \
    --mount=type=bind,source=requirements,target=/workspace/requirements \
    pip install --no-build-isolation --no-cache-dir '.[all]' && \
    # Install nemo-run separately since it conflicts with nvidia-pytriton
    pip install nemo-run

# Install development versions
RUN pip install --no-cache-dir --upgrade --force-reinstall --no-deps \
    git+https://github.com/NVIDIA/Megatron-LM.git@54afff44f29e1117b2057ced6fa5be583e35cb7b \
    nemo_toolkit[automodel,common-only,nlp-only,eval,multimodal-only,asr-only]@git+https://github.com/NVIDIA/NeMo.git@0fb6a3c1da785c1c3c147fcae00d671189b2b9c9


