name: Push hello.md

on:
  push:

jobs:
  push-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_ID }}
          private-key: ${{ secrets.BOT_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create hello.md
        run: echo "# Hello from GitHub Actions" > hello.md

      - name: Commit and push hello.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hello.md
          git commit -m "Add hello.md from workflow" || echo "No changes to commit"
          git push
